# Browser App
# Displays web search and reading activity from AI agents

id: browser
name: Browser
icon: globe
description: Watch AI search the web and read pages

# Primary entity type for routing
entity: web

# Capabilities this app handles (for activity routing)
handles:
  - web_search
  - web_read

views:
  # Search results view - shows web_search activity
  search:
    capability: web_search
    title: Browser
    toolbar:
      - component: url-bar
        props:
          mode: search
          value: "{{activity.request.query}}"
          loading: "{{activity.pending}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: list
        data:
          source: activity
          filter: web_search
        item_component: items/search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # Read view - shows web_read activity
  read:
    capability: web_read
    title: "{{activity.response.title}}"
    toolbar:
      - component: url-bar
        props:
          mode: url
          value: "{{activity.request.url}}"
          loading: "{{activity.pending}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: layout/scroll-area
        children:
          - component: markdown
            props:
              content: "{{activity.response.content}}"
              loading: "{{activity.pending}}"
        footer:
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

default_view: search
